<a href="https://colab.research.google.com/github/devika1910/AIML_Bootcamp/blob/main/Day10SMSspam(allAlgorithms).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#naive bayes works on spam filters,text ananlyisis,medical dignosis
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('/content/SMSSpamCollection',sep='\t',header=None,names=['label','message'])

In [7]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.shape

(5572, 2)

In [9]:
#data preprocessing
#method1
df['label']=df.label.map({'ham':0,'spam':1})

In [10]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [11]:
#bag of word
#define the documents
'''documents=['Hello, how are you',
           'Win money , win from home.',
           'call me now.',
           'Hello,call hello you tomorrow?']
           #apply co
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
print(count_vector)'''

"documents=['Hello, how are you',\n           'Win money , win from home.',\n           'call me now.',\n           'Hello,call hello you tomorrow?']\n           #apply co\nfrom sklearn.feature_extraction.text import CountVectorizer\ncount_vector=CountVectorizer()\nprint(count_vector)"

In [12]:
'''#fit_transform,transform
count_vector.fit(documents)'''

'#fit_transform,transform\ncount_vector.fit(documents)'

In [ ]:
'''n=count_vector.get_feature_names()
print(n)'''

In [14]:
'''doc_array=count_vector.transform(documents).toarray()'''


'doc_array=count_vector.transform(documents).toarray()'

In [15]:
'''doc_array'''

'doc_array'

In [16]:
'''#converting this array into a dataframe -for understanding
freq_table=pd.DataFrame(data=doc_array,columns=n)'''


'#converting this array into a dataframe -for understanding\nfreq_table=pd.DataFrame(data=doc_array,columns=n)'

In [17]:
'''freq_table'''

'freq_table'

In [18]:
#load the data
X = df.iloc[:,-1:].values#independent -- message
Y = df.iloc[:,:-1].values #dependent -- label

In [21]:
X

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [22]:
#spilt the data set--> method 2
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1,shuffle=True)

In [23]:
X_train

array([["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?"],
       ['If you r @ home then come down within 5 min'],
       ["When're you guys getting back? G said you were thinking about not staying for mcr"],
       ...,
       ['CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES'],
       ['Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence'],
       ['K k:) sms chat with me.']], dtype=object)

In [24]:
X_train.shape

(4457, 1)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()

#transform the training data into freq vectors and return the matrix

training_data = count_vector.fit_transform(X_train.flatten())

#transform the testing data into freq vectors and return the matrix

testing_data = count_vector.transform(X_test.flatten())

In [26]:
training_data

<4457x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 59028 stored elements in Compressed Sparse Row format>

In [27]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()

In [28]:
model.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [29]:
y_pred=model.predict(testing_data)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [34]:
print("Predicted value for training data:",model.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model.score(testing_data,Y_test)*100)

Predicted value for training data: 99.23715503702041
Predicted value for testing data: 99.01345291479821


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FP FN TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model.predict(training_data))
print(cm1)

confusion matrix for testing data
[[965   3]
 [  8 139]]
confusion matrix for traning data
[[3843   14]
 [  20  580]]


In [36]:
#randomforest
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [37]:
y_pred=model2.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [38]:
print("Predicted value for training data:",model2.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model2.score(testing_data,Y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 98.29596412556054


In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model2.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 19 128]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [40]:
#decisiontree
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier()

In [41]:
model3.fit(training_data,Y_train)


DecisionTreeClassifier()

In [42]:
print("Predicted value for training data:",model3.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model3.score(testing_data,Y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 96.95067264573991


In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model3.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 19 128]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [44]:
#logisticregression
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression()

In [45]:
model4.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [46]:
print("Predicted value for training data:",model4.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model4.score(testing_data,Y_test)*100)

Predicted value for training data: 99.75319721785955
Predicted value for testing data: 98.9237668161435


In [47]:
y_pred=model4.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model4.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 11 136]]
confusion matrix for traning data
[[3857    0]
 [  11  589]]


In [49]:
#knn
from sklearn.neighbors import KNeighborsClassifier
model5=KNeighborsClassifier()

In [50]:
model5.fit(training_data,Y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [51]:
print("Predicted value for training data:",model5.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model5.score(testing_data,Y_test)*100)

Predicted value for training data: 93.56069104778999
Predicted value for testing data: 92.37668161434978


In [52]:
y_pred=model5.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model5.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 85  62]]
confusion matrix for traning data
[[3857    0]
 [ 287  313]]


In [54]:
#svc
from sklearn.svm import SVC
model6=SVC()
model6.fit(training_data,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [55]:
print("Predicted value for training data:",model6.score(training_data,Y_train)*100)
print("Predicted value for testing data:",model6.score(testing_data,Y_test)*100)

Predicted value for training data: 99.50639443571909
Predicted value for testing data: 98.7443946188341


In [56]:
y_pred=model6.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,model6.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 13 134]]
confusion matrix for traning data
[[3857    0]
 [  22  578]]
